name: admin-deploy

on:
    push:
        branches:
            - main
        paths:
            - "allapps/admin/**"

defaults:
    run:
        working-directory: allapps/admin

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run build

            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                  aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}
                  aws-region: ap-south-1
            - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/admin/latest

            - name: Create CloudFront invalidation
              uses: josemando/aws-cloudfront-create-invalidation@v1
              with:
                  distribution-id: ${{secrets.AWS_CLOUDFRONT_DISTRIBUITION_KEY}}
                  paths: /admin/latest/remoteEntry.js
