name: container-deploy

on:
  push:
    branches: 
      - main
    paths:
      - "allaps/container/**"

defaults:
  run:
    working-directory: allaps/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build